
services:
  db:
    image: postgres:14.8-alpine3.18
    container_name: postgres
    restart: always
    env_file:
      - .env
    networks:
      - app
    ports:
      - 5432:5432 # in production, use only 5432, this exposes the db to the host machine, userful for development
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:z
      # if data resiliency is a must, add - /path/to/data::/var/lib/postgresql/data:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 10s
      retries: 6
  clash-of-nations:
    build: .
    container_name: clash-of-nations
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_URL=db
    networks:
      - app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080 # don't do this in production, use a reverse proxy like nginx

networks:
  app:
    driver: bridge
    name: app

